language: php
php:
  - 7
  
services:
  - beanstalkd
  - mongodb
  - memcached
  - redis-server
  - rabbitmq-server

before_script:
  - pecl install mongo
  - pecl install redis
  - curl -sS https://getcomposer.org/installer | php -- --filename=composer
  - chmod +x composer
  - composer install

script: 
  - php vendor/bin/phpunit --coverage-text

branches:
  only:
    - master
 
