language: php
php:
  - "7.0"
services:
  - beanstalkd
  - mongodb
  - memcached
  - redis-server
  - rabbitmq-server
    
sudo: required
before_script:
  - sudo apt-get install php*-dev
  - sudo pecl install mongo
  - sudo pecl install redis
  - curl -sS https://getcomposer.org/installer | php -- --filename=composer
  - chmod +x composer
  - composer install

script: 
  - php vendor/bin/phpunit --coverage-text

branches:
  only:
    - master
 
