sudo: required

language: php

php:
  - 7
  
matrix:
  fast_finish: true
  
services:
  - beanstalkd
  - mongodb
  - redis-server
  - rabbitmq-server
  
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
    
before_script:
  - sudo apt-get install beanstalkd 
  - curl -sS https://getcomposer.org/installer | php -- --filename=composer
  - chmod +x composer
  - composer install

script: 
  - php vendor/bin/phpunit --coverage-text

branches:
  only:
    - master
 
