sudo: required

language: php

php:
  - 7
  
matrix:
  fast_finish: true
  
services:
  - beanstalkd
  - mongodb
  - redis-server
  - rabbitmq-server
  
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
    
before_script:
  - sudo apt-get install beanstalkd 
  - sudo echo "BEANSTALKD_LISTEN_ADDR=127.0.0.1" >> /etc/default/beanstalkd && sudo echo "BEANSTALKD_LISTEN_PORT=11300" >> /etc/default/beanstalkd && sudo service beanstalkd restart
  - echo 'extension="mongodb.so"' >> myconfig.ini && echo 'extension="redis.so"' >> myconfig.ini && phpenv config-add myconfig.ini
  - curl -sS https://getcomposer.org/installer | php -- --filename=composer
  - chmod +x composer
  - composer install

script: 
  - php vendor/bin/phpunit --coverage-text

branches:
  only:
    - master
 
