language: php
php:
  - "7.0"
sudo: required
before_script:
  - sudo apt-get install rabbitmq-server beanstalkd redis-server
  - sudo pecl install mongo
  - sudo pecl install redis
  - curl -sS https://getcomposer.org/installer | php -- --filename=composer
  - chmod +x composer
  - composer install

script: 
  - php vendor/bin/phpunit --coverage-text

branches:
  only:
    - master
 
